// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTMMC.Services;

namespace TTMMC.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190117142614_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TTMMC.Models.DBModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Code");

                    b.Property<string>("Email");

                    b.Property<string>("FiscalCode");

                    b.Property<string>("Name");

                    b.Property<string>("PEC");

                    b.Property<string>("Phone");

                    b.Property<string>("Province");

                    b.Property<string>("State");

                    b.Property<string>("Town");

                    b.Property<string>("VAT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TTMMC.Models.DBModels.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("X");

                    b.Property<string>("Y");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TTMMC.Models.DBModels.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("MouldId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MouldId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("TTMMC.Models.DBModels.Mould", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int?>("LocationId");

                    b.Property<int>("Machine");

                    b.Property<string>("Master");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LocationId");

                    b.ToTable("Moulds");
                });

            modelBuilder.Entity("TTMMC.Models.DBModels.Material", b =>
                {
                    b.HasOne("TTMMC.Models.DBModels.Mould")
                        .WithMany("Materials")
                        .HasForeignKey("MouldId");
                });

            modelBuilder.Entity("TTMMC.Models.DBModels.Mould", b =>
                {
                    b.HasOne("TTMMC.Models.DBModels.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("TTMMC.Models.DBModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
